language: node_js

node_js:
  - 12.9.1

before_deploy:
  - npm install
  - npm install --global typescript

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: npm publish
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "$NPM_AUTH_EMAIL"
        api_key: "$NPM_AUTH_TOKEN"
      on:
        branch: master
